---

- hosts: servers
  user: blaise
  become: yes
  become_user: root
  become_method: sudo

  vars:
    app_name: MahjongSite
    repo_url: https://github.com/BlaiseRitchie/MahjongSite.git
    nginx_dir: /usr/share/nginx
    file: main.py
    user: www-data

  tasks:
    - name: Install Software
      apt:
        update_cache: yes
        name:
          - nginx
          - virtualenv
          - supervisor
          - uwsgi
          - uwsgi-plugin-python
          - python3-pip
          - libsqlite3-dev

    - name: Create nginx config
      copy: src=nginx.conf dest=/etc/nginx/nginx.conf

    - name: Reload nginx
      service: name=nginx state=reloaded

    - name: deploy code from repository
      git: repo={{ repo_url }} dest="{{ nginx_dir }}/{{ app_name }}"

    - name: Copy settings file
      copy: src=settings.py dest="{{ nginx_dir }}/{{ app_name }}/settings.py"

    - name: Install dependencies
      pip: requirements="{{ nginx_dir }}/{{ app_name }}/requirements.txt" virtualenv="{{ nginx_dir }}/{{ app_name }}"

    - name: Fix permissions
      file: path="{{ nginx_dir }}/{{ app_name }}" owner={{ user }} group={{ user }} state=directory recurse=yes

    - name: create supervisor program config
      template: src="{{ playbook_dir }}/supervisor.j2" dest="/etc/supervisor/conf.d/{{ app_name }}.conf"
      notify:
        - restart supervisor

    - name: create nginx site config
      template: src="{{ playbook_dir }}/nginx.j2" dest="/etc/nginx/vhosts.d/{{ app_name }}.conf"
      notify:
        - reload nginx

  handlers:
    - name: restart supervisor
      service: name=supervisor state=restart

    - name: reload nginx
      service: name=nginx state=reloaded
