---

- hosts: servers
  user: blaise
  become: yes
  become_user: root
  become_method: sudo

  vars:
    app_name: MahjongSite
    repo_url: https://github.com/BlaiseRitchie/MahjongSite.git
    nginx_dir: /usr/share/nginx
    file: run.sh
    user: www-data

  tasks:
    - name: Install Software
      apt:
        update_cache: yes
        name:
          - nginx
          - supervisor
          - python3-pip
          - virtualenv
          - libgit2-dev
          - libsqlite3-dev

    - name: Create nginx config
      copy: src=nginx.conf dest=/etc/nginx/nginx.conf

    - name: Create nginx vhosts dir
      file: path=/etc/nginx/vhosts.d state=directory

    - name: Reload nginx
      service: name=nginx state=reloaded

    - name: deploy code from repository
      git: repo={{ repo_url }} dest="{{ nginx_dir }}/{{ app_name }}" version="master"

    - name: Check if mysettings.py exists
      stat:
        path: ../mysettings.py
      register: stat_result

    - name: Copy mysettings.py file
      copy: src=../mysettings.py dest="{{ nginx_dir }}/{{ app_name }}/mysettings.py"
      when: stat_result.stat.exists == True

    - name: Install dependencies
      pip:
        virtualenv: "{{ nginx_dir }}/{{ app_name }}/venv"
        virtualenv_python: "python3"
        requirements: "{{ nginx_dir }}/{{ app_name }}/requirements.txt"

    - name: Fix permissions
      file: path="{{ nginx_dir }}/{{ app_name }}" owner={{ user }} group={{ user }} state=directory recurse=yes

    - name: create supervisor program config
      template: src="{{ playbook_dir }}/supervisor.j2" dest="/etc/supervisor/conf.d/{{ app_name }}.conf"
      notify:
        - restart supervisor

    - name: Ensure tornado_params file is in place
      copy: src="{{ playbook_dir }}/tornado_params" dest=/etc/nginx/tornado_params

    - name: create nginx site config
      template: src="{{ playbook_dir }}/nginx.j2" dest="/etc/nginx/vhosts.d/{{ app_name }}.conf"
      notify:
        - reload nginx

  handlers:
    - name: restart supervisor
      supervisorctl:
        name: "{{ app_name }}:"
        state: restarted

    - name: reload nginx
      service: name=nginx state=reloaded
