---

- hosts: servers
  user: blaise
  become: yes
  become_user: root
  become_method: sudo

  tasks:
    - name: Install Software
      apt:
        update_cache: yes
        name:
          - nginx
          - supervisor
          - python3-pip

    - name: Create nginx config
      copy: src=nginx.conf dest=/etc/nginx/nginx.conf

    - name: Reload nginx
      service: name=nginx state=reloaded
